jobs:
  when:
    condition:
      not-equal: [ main, << pipeline.git.branch >> ]
  build:
    docker:
      - image: rabilrbl/aosp-build
    steps:
      - checkout
      - run:
         name: Build ROiM
         command: curl https://raw.githubusercontent.com/Jayzee-Zee/build_scripts/SETUP/setup.sh | bash
          curl https://raw.githubusercontent.com/Jayzee-Zee/build_scripts/CipherOS/build.sh | bash
