jobs:
  when:
    condition:
      not-equal: [ main, << pipeline.git.branch >> ]
  build:
    docker:
      - image: rabilrbl/aosp-build
    steps:
      - checkout
      - run:
         name: Build ROiM
         command: wget https://raw.githubusercontent.com/Jayzee-Zee/build_scripts/SETUP/setup.sh
      - run: 
         name : exec
         command: bashsetup.sh
