jobs:
  when:
    condition:
      not-equal: [ main, << pipeline.git.branch >> ]
  build:
    docker:
      - image: rabilrbl/aosp-build
    steps:
      - checkout
      - run:
         name: setup
         command: wget https://raw.githubusercontent.com/Jayzee-Zee/build_scripts/SETUP/setup.sh && sudo chmod +x setup.sh && sudo ./setup.sh
      - run: 
         name : exec
         command: bash setup.sh
