name: Build Android ROM

on:
  push:
    branches:
      - main  # Trigger build on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            curl \
            openjdk-11-jdk \
            lzop \
            bc \
            bison \
            build-essential \
            libncurses5-dev \
            libncursesw5-dev \
            zlib1g-dev \
            liblz4-tool \
            liblzma-dev \
            gawk \
            flex \
            gettext \
            unzip \
            img2simg

      - name: Set up Android build environment
        run: |
          mkdir -p $HOME/android
          cd $HOME/android
          git clone https://android.googlesource.com/platform/manifest
          cd manifest
          repo init -u https://android.googlesource.com/platform/manifest -b android-11.0.0_r1
          repo sync -j$(nproc)

      - name: Build the ROM
        run: |
          cd $HOME/android
          source build/envsetup.sh
          lunch aosp_arm-eng
          m -j$(nproc)
          
      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-rom
          path: $HOME/android/out/target/product/*
          
