name: Build Android ROM

on:
  push:
    branches:
      - main  # Trigger build on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            curl \
            openjdk-11-jdk \
            lzop \
            bc \
            bison \
            build-essential \
            libncurses5-dev \
            libncursesw5-dev \
            zlib1g-dev \
            liblz4-tool \
            liblzma-dev \
            gawk \
            flex \
            gettext \
            unzip \
            img2simg

      - name: Set up Android build environment
        run: |
          cd ~/
          wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip
          # add Android SDK platform tools to path
         if [ -d "$HOME/platform-tools" ] ; then
         PATH="$HOME/platform-tools:$PATH"
         fi
         source ~/.profile
         cd ~/
         git clone https://github.com/akhilnarang/scripts
         cd scripts
         ./setup/android_build_env.sh
         cd ~/
         mkdir -p ~/bin
         mkdir -p ~/android
         curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
         chmod a+x ~/bin/repo
         git config --global user.email "salitagwapo@gmail.com"
         git config --global user.name "Jayzee"
        curl https://raw.githubusercontent.com/Jayzee-Zee/build_scripts/CipherOS/build.sh | bash
